package Npl.content;

import arc.Core;
import arc.func.Cons;
import arc.graphics.Color;
import arc.graphics.g2d.Draw;
import arc.graphics.g2d.Fill;
import arc.graphics.g2d.Lines;
import arc.graphics.g2d.TextureRegion;
import arc.math.Angles;
import arc.math.Interp;
import arc.math.Mathf;
import arc.math.Rand;
import arc.math.geom.Rect;
import arc.math.geom.Vec2;
import arc.scene.ui.layout.Table;
import arc.struct.IntMap;
import arc.struct.ObjectSet;
import arc.struct.Seq;
import arc.util.Time;
import arc.util.Tmp;
import mindustry.Vars;
import mindustry.ai.UnitCommand;
import mindustry.ai.types.*;
import mindustry.ai.*;
import mindustry.audio.SoundLoop;
import mindustry.content.Fx;
import mindustry.content.Items;
import mindustry.content.StatusEffects;
import mindustry.entities.*;
import mindustry.entities.abilities.*;
import mindustry.entities.bullet.*;
import mindustry.entities.effect.*;
import mindustry.entities.effect.MultiEffect;
import mindustry.entities.part.DrawPart;
import mindustry.entities.part.HaloPart;
import mindustry.entities.part.RegionPart;
import mindustry.entities.part.ShapePart;
import mindustry.entities.pattern.*;
import mindustry.entities.units.WeaponMount;
import mindustry.game.Team;
import mindustry.gen.*;
import mindustry.graphics.Drawf;
import mindustry.graphics.Layer;
import mindustry.graphics.MultiPacker;
import mindustry.graphics.Pal;
import mindustry.type.StatusEffect;
import mindustry.type.UnitType;
import mindustry.type.Weapon;
import mindustry.type.unit.*;
import mindustry.type.weapons.*;
import mindustry.world.meta.BlockFlag;
import mindustry.world.meta.Env;
import Npl.content.*;
import Npl.newSth.Type.*;
import Npl.newSth.AI.*;
import Npl.newSth.*;
import static arc.graphics.g2d.Draw.*;
import static arc.graphics.g2d.Lines.*;
import static arc.math.Angles.*;
import static mindustry.Vars.*;

public class CuteUnitTypes {
    public static UnitType SmallMoonLight,Wilder;
    public static void load(){
        SmallMoonLight = new UnitType("SmallMoonLight"){{
            constructor =  UnitEntity::create;
            EntityMapping.nameMap.put(name,constructor);
            flying = true;
            drawCell = true;
            circleTarget = true;
            itemCapacity = 45;
            health = 2000;
            speed = 5f;
            trailLength = 8;
            researchCostMultiplier = 0.50f;
            flyingLayer = Layer.flyingUnit;
            armor = 1000;hitSize = 12f;alwaysUnlocked = false;
            isEnemy = false;playerControllable =false;logicControllable =false;
        }};
        Wilder = new UnitType("Wilder"){{
            constructor=LegsUnit::create;
            EntityMapping.nameMap.put(name, constructor);
            health = 2100;
            speed = 2.85f;
            researchCostMultiplier = 1f;
            armor = 900;
            isEnemy = false;
            hitSize = 12f;
            legCount = 4;
            legMoveSpace = 1.45f;
            lockLegBase = true;
            legContinuousMove = true;
            legGroupSize = 2;
            legPairOffset = 5f;
            legLength = 10;
            legExtension = -6f;
            legBaseOffset = 25f;
            legSpeed = 4f;
            legLengthScl = 1.5f;
            stepShake = 1.5f;
            rippleScale = 1.25f;
            legSplashDamage = 5f;
            legSplashRange  = 8f;
            hovering = true;
            legPhysicsLayer = true;
            rotateMoveFirst = true;
            healFlash = true;
            shadowElevation = 0.7f;
            drownTimeMultiplier = 2f;
            targetAir = true;
            targetGround = true;
        }};
    }
}
